<!DOCTYPE html>
<html lang="en">

<head>
  <title>Async Await</title>
</head>

<body>
  <script>

    function breathe(amount) {
      return new Promise((resolve, reject) => {
        if (amount < 500) {
          reject("That is too small of a value!");
        }
        setTimeout(() => resolve(`Done for ${amount} ms`), amount);
      });
    }

    // Basics - using `try...catch` for error handling
    // async function go() {
    //   // error handling with `try...catch`
    //   try {
    //     console.log("start");
    //     let res = await breathe(1000); // The resolved value from the promise
    //     console.log(res);              // put into the `res` variable 
    //     res = await breathe(300);
    //     console.log(res);
    //     res = await breathe(2000);
    //     console.log(res);
    //     res = await breathe(500);
    //     console.log(res);
    //     console.log("end");
    //   } catch(err) {
    //     console.error("Ohhh nooooo!!");
    //     console.error(err); // That is too small of a value!
    //   }
    // }

    /*
      Using a higher-order function for error handling.
      Great for handling several errors in a similar way instead
      of using a `try...catch` for every single one. 
      Higher-order functions are functions that accept other functions
      as arguments and/or return functions as output.
    */
    
      function catchErrors(fn) {
        return function(...args) { // using rest and spread for the args
          return fn(...args).catch((err) => {
            console.error("Ohhh nooooo!!");
            console.error(err);
          });
        }
      }

    async function go(name, familyName) {  // adding in some parameters
        console.log(`Starting for ${name} ${familyName}!`);
        let res = await breathe(1000);
        console.log(res);
        res = await breathe(300);
        console.log(res);
        res = await breathe(2000);
        console.log(res);
        res = await breathe(500);
        console.log(res);
        console.log("end");
    }

    const wrappedFunctions = catchErrors(go);

    wrappedFunctions("Steve", "Urban"); // Since rest/spread was
    // used, any number of arguments can be used.

    /*
      start
      Done for 1000 ms
      Done for 600 ms
      Done for 2000 ms
      Done for 500 ms
      end
     */

  </script>
</body>

</html>